baseURL = "https://www.thesofa.fr/"
languageCode = "en-us"
title = "The Sofa"
# theme = "ananke"

[menu]
  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio/"
    weight = -110
  [[menu.main]]
    identifier = "open-source"
    name = "Open-Source"
    url = "/open-source/"
    weight = -100
